//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookWcfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSessionReservation
    {
        public int Id { get; set; }
        public int MovieSessionId { get; set; }
        public int MovieSeatTypeId { get; set; }
        public string SeatPrefix { get; set; }
        public string SeatSuffix { get; set; }
        public string SeatCode { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int UserId { get; set; }
        public string SessionId { get; set; }
        public Nullable<int> MovieTheatrePlaceTemplateDetailsId { get; set; }
        public Nullable<int> Block { get; set; }
    
        public virtual MovieSeatType MovieSeatType { get; set; }
        public virtual MovieSession MovieSession { get; set; }
        public virtual User User { get; set; }
    }
}
