//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookWcfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTheatrePlaceTemplateBlock
    {
        public int MovieTheaterBlockId { get; set; }
        public string MovieTheaterBlockName { get; set; }
        public Nullable<int> MovieTheatrePlaceTemplateId { get; set; }
        public Nullable<int> BlockIndex { get; set; }
    
        public virtual MovieTheatrePlaceTemplate MovieTheatrePlaceTemplate { get; set; }
    }
}
