//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookWcfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTheatrePlaceTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieTheatrePlaceTemplate()
        {
            this.MovieTheatrePlace = new HashSet<MovieTheatrePlace>();
            this.MovieTheatrePlaceTemplateDetails = new HashSet<MovieTheatrePlaceTemplateDetails>();
            this.MovieTheatrePlaceTemplateBlock = new HashSet<MovieTheatrePlaceTemplateBlock>();
        }
    
        public int MovieTheatrePlaceTemplateId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Block { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTheatrePlace> MovieTheatrePlace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTheatrePlaceTemplateDetails> MovieTheatrePlaceTemplateDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTheatrePlaceTemplateBlock> MovieTheatrePlaceTemplateBlock { get; set; }
    }
}
