//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookWcfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTicket
    {
        public int MovieTicketSaleId { get; set; }
        public int MovieTicketId { get; set; }
        public int MovieSeatTypeId { get; set; }
        public int MovieTariffId { get; set; }
        public string SeatPrefix { get; set; }
        public string SeatSuffix { get; set; }
        public string SeatCode { get; set; }
        public decimal Amount { get; set; }
        public bool IsPrinted { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string PrintLocation { get; set; }
        public string BarcodeNumber { get; set; }
        public string TicketOrder { get; set; }
        public string CustomerInfo { get; set; }
        public string BlockName { get; set; }
    
        public virtual MovieSeatType MovieSeatType { get; set; }
        public virtual MovieTariff MovieTariff { get; set; }
        public virtual MovieTicketSale MovieTicketSale { get; set; }
    }
}
