//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookWcfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieFormat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieFormat()
        {
            this.Movie_MovieFormat = new HashSet<Movie_MovieFormat>();
            this.MovieSession_MovieFormat = new HashSet<MovieSession_MovieFormat>();
        }
    
        public int MovieFormatId { get; set; }
        public string MovieFormatCode { get; set; }
        public string MovieFormatName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie_MovieFormat> Movie_MovieFormat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieSession_MovieFormat> MovieSession_MovieFormat { get; set; }
    }
}
