//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookWcfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTicketSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieTicketSale()
        {
            this.MovieTicket = new HashSet<MovieTicket>();
            this.MovieTicketSaleOption = new HashSet<MovieTicketSaleOption>();
            this.MovieTicketSalePayment = new HashSet<MovieTicketSalePayment>();
        }
    
        public int MovieTicketSaleId { get; set; }
        public int MovieSessionId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Completed { get; set; }
        public int UserId { get; set; }
        public string SessionId { get; set; }
        public string TransactionId { get; set; }
    
        public virtual MovieSession MovieSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTicket> MovieTicket { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTicketSaleOption> MovieTicketSaleOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieTicketSalePayment> MovieTicketSalePayment { get; set; }
    }
}
