//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookWcfService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup_User
    {
        public int Id { get; set; }
        public int UserGroupId { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
