//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcenteKullanici
    {
        public int Id { get; set; }
        public int AcenteId { get; set; }
        public string AcenteKodu { get; set; }
        public string KullaniciAdi { get; set; }
        public string Parola { get; set; }
        public string ParolaHash { get; set; }
        public string MailAdres { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> LastSendTime { get; set; }
        public Nullable<bool> IsSend { get; set; }
    }
}
