//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADRES_BILGILERI
    {
        public int ID { get; set; }
        public Nullable<int> PERID { get; set; }
        public string ADRES_MAH { get; set; }
        public string ADRES_CAD { get; set; }
        public string ADRES_SOK { get; set; }
        public string ADRES_NO { get; set; }
        public string ADRES_BLOK { get; set; }
        public string ADRES_ILCE { get; set; }
        public string ADRES_IL { get; set; }
        public string TEL_SABIT { get; set; }
        public string TEL_CEP { get; set; }
        public string TEL_YAKIN { get; set; }
    
        public virtual PERSONEL PERSONEL { get; set; }
    }
}
