//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class AR_KullaniciOturum
    {
        public int Id { get; set; }
        public string Oturum { get; set; }
        public string Kodu { get; set; }
        public System.DateTime GirisZamani { get; set; }
    
        public virtual AR_Kullanici AR_Kullanici { get; set; }
    }
}
