//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class AR_Parametre
    {
        public string Parametre { get; set; }
        public Nullable<decimal> SmallMoney { get; set; }
        public string NVarChar { get; set; }
        public Nullable<int> Int { get; set; }
    }
}
