//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class AR_Rezervasyon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AR_Rezervasyon()
        {
            this.AR_Bileklik = new HashSet<AR_Bileklik>();
        }
    
        public int Id { get; set; }
        public string RezervasyonKodu { get; set; }
        public string Durum { get; set; }
        public string HizmetTuruKodu { get; set; }
        public string KurumTuruKodu { get; set; }
        public string LokasyonKodu { get; set; }
        public string RezerveEden { get; set; }
        public string RezerveEdenKisiAdi { get; set; }
        public string RezerveEdenKisiTel { get; set; }
        public string KafileBasiAdi { get; set; }
        public string KafileBasiTel { get; set; }
        public string MisafirAdi { get; set; }
        public Nullable<System.DateTime> GelisTarihi { get; set; }
        public Nullable<System.TimeSpan> GelisSaati { get; set; }
        public Nullable<int> GelecekKisiSayisi { get; set; }
        public string Aciklama { get; set; }
        public string OdemeTuru { get; set; }
        public decimal KisiBasiFiyatYerliYetiskin { get; set; }
        public decimal KisiBasiFiyatYerliCocuk { get; set; }
        public decimal KisiBasiFiyatYabanciYetiskin { get; set; }
        public decimal KisiBasiFiyatYabanciCocuk { get; set; }
        public Nullable<byte> BileklikTarifeYerliYetiskin { get; set; }
        public Nullable<byte> BileklikTarifeYerliCocuk { get; set; }
        public Nullable<byte> BileklikTarifeYerliUcretsiz { get; set; }
        public Nullable<byte> BileklikTarifeYabanciYetiskin { get; set; }
        public Nullable<byte> BileklikTarifeYabanciCocuk { get; set; }
        public Nullable<byte> BileklikTarifeYabanciUcretsiz { get; set; }
        public string SonDegistiren { get; set; }
        public Nullable<System.DateTime> SonDegisiklik { get; set; }
        public int GelenKisiSayisiYerliYetiskin { get; set; }
        public int GelenKisiSayisiYerliCocuk { get; set; }
        public int GelenKisiSayisiYerliUcretsiz { get; set; }
        public int GelenKisiSayisiYabanciYetiskin { get; set; }
        public int GelenKisiSayisiYabanciCocuk { get; set; }
        public int GelenKisiSayisiYabanciUcretsiz { get; set; }
        public decimal ToplamTutar { get; set; }
        public decimal ToplamNakit { get; set; }
        public decimal ToplamKart { get; set; }
        public decimal ToplamKomisyon { get; set; }
        public string TutanakOperator { get; set; }
        public Nullable<System.DateTime> TutanakTarihi { get; set; }
        public string TutanakKiosk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AR_Bileklik> AR_Bileklik { get; set; }
        public virtual AR_Kiosk AR_Kiosk { get; set; }
        public virtual AR_Kullanici AR_Kullanici { get; set; }
        public virtual AR_KurumTuru AR_KurumTuru { get; set; }
        public virtual AR_Lokasyon AR_Lokasyon { get; set; }
        public virtual AR_Operator AR_Operator { get; set; }
    }
}
