//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAKIYE_YUKLEME_COP
    {
        public int ID { get; set; }
        public Nullable<int> PERID { get; set; }
        public Nullable<long> KARTID { get; set; }
        public Nullable<int> BAKIYE { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SICILNO { get; set; }
        public string YUKNOKID { get; set; }
    }
}
