//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAKIYE_YUKLEME_IADE
    {
        public int ID { get; set; }
        public Nullable<int> PERID { get; set; }
        public Nullable<long> KARTID { get; set; }
        public Nullable<int> ESKI_BAKIYE { get; set; }
        public Nullable<int> YUKLENEN_BAKIYE { get; set; }
        public Nullable<int> YENI_BAKIYE { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SICILNO { get; set; }
        public string YUKNOKID { get; set; }
        public Nullable<System.DateTime> IPTAL_TARIH { get; set; }
        public bool IPTAL_EDILDI { get; set; }
        public string IPTAL_NEDENI { get; set; }
        public string IPTAL_EDEN { get; set; }
        public string NAKIT_KUR { get; set; }
        public Nullable<decimal> NAKIT_TUTAR { get; set; }
        public string KART_KUR { get; set; }
        public Nullable<decimal> KART_TUTAR { get; set; }
        public string TOPLAM_KUR { get; set; }
        public Nullable<decimal> TOPLAM_TUTAR { get; set; }
        public string ISLEMTURU { get; set; }
        public Nullable<decimal> NAKIT_REEL { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<System.DateTime> IADE_TARIH { get; set; }
        public string IADE_SICILNO { get; set; }
        public string IADE_YUKNOKID { get; set; }
    }
}
