//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAKIYE_YUKLEME_DUZELTME
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string YUKNOKID { get; set; }
        public string KULLANICI { get; set; }
        public Nullable<byte> TARIFEID { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string SICILNO { get; set; }
        public Nullable<System.DateTime> SONDEGISIKLIK { get; set; }
    }
}
