//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAKIYE_YUKLEME_BONUS_TANIM
    {
        public int ID { get; set; }
        public System.DateTime TARIHBAS { get; set; }
        public System.DateTime TARIHBIT { get; set; }
        public decimal TUTARMIN { get; set; }
        public decimal TUTARMAX { get; set; }
        public decimal TUTARBONUS { get; set; }
        public string SICILNO { get; set; }
        public Nullable<decimal> YUZDE { get; set; }
    }
}
