//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILET_ODEME
    {
        public int ODEMEID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SICILNO { get; set; }
        public string YUKNOKID { get; set; }
        public string NAKIT_KUR { get; set; }
        public Nullable<decimal> NAKIT_TUTAR { get; set; }
        public string KART_KUR { get; set; }
        public Nullable<decimal> KART_TUTAR { get; set; }
        public string TOPLAM_KUR { get; set; }
        public Nullable<decimal> TOPLAM_TUTAR { get; set; }
        public string KREDI_KUR { get; set; }
        public Nullable<decimal> KREDI_TUTAR { get; set; }
        public string KAMPANYA_KUR { get; set; }
        public Nullable<decimal> KAMPANYA_TUTAR { get; set; }
        public string KAMPANYA_KODU { get; set; }
        public Nullable<decimal> NAKIT_REEL { get; set; }
        public Nullable<decimal> KOMISYON_TUTAR { get; set; }
        public Nullable<double> KOMISYON_YUZDE { get; set; }
        public Nullable<decimal> KOMISYON_TOPLAM { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> VERGISIZ { get; set; }
    }
}
