//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiletKotaKod
    {
        public int Id { get; set; }
        public int KotaId { get; set; }
        public string Kod { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public int KullaniciId { get; set; }
        public bool Kullanildi { get; set; }
        public Nullable<System.DateTime> KullanilmaTarihi { get; set; }
    
        public virtual BiletKota BiletKota { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
