//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILET
    {
        public int ID { get; set; }
        public string BARKODNO { get; set; }
        public Nullable<System.DateTime> TANIM_TARIH { get; set; }
        public string TANIMLAYAN { get; set; }
        public string YUKNOKID { get; set; }
        public Nullable<byte> TARIFEID { get; set; }
        public string TOPLAM_KUR { get; set; }
        public Nullable<decimal> TOPLAM_TUTAR { get; set; }
        public Nullable<bool> GECERLIMI { get; set; }
        public Nullable<int> ODEMEID { get; set; }
        public Nullable<System.DateTime> GECERLILIK_BASLANGIC { get; set; }
        public Nullable<System.DateTime> GECERLILIK_BITIS { get; set; }
        public Nullable<int> GECISBILETID { get; set; }
        public string MISAFIR { get; set; }
        public string ALAN1 { get; set; }
        public string ALAN2 { get; set; }
        public string ALAN3 { get; set; }
        public string ALAN4 { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> VERGISIZ { get; set; }
    }
}
