//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILET_TARIFE
    {
        public byte TARIFEID { get; set; }
        public string TARIFEADI { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<System.TimeSpan> GUNSONU { get; set; }
        public Nullable<bool> MISAFIRKAYDI { get; set; }
        public string KAMPANYAID { get; set; }
        public string GUNLER { get; set; }
    }
}
