//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOLUM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOLUM()
        {
            this.PERSONEL = new HashSet<PERSONEL>();
        }
    
        public Nullable<int> KAMPUSID { get; set; }
        public Nullable<int> FAKULTEID { get; set; }
        public int BOLUMID { get; set; }
        public string BOLUMADI { get; set; }
    
        public virtual FAKULTE FAKULTE { get; set; }
        public virtual KAMPUS KAMPUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONEL> PERSONEL { get; set; }
    }
}
