//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BURS
    {
        public int ID { get; set; }
        public string SICILNO { get; set; }
        public Nullable<int> PERID { get; set; }
        public Nullable<int> BAKIYE { get; set; }
        public Nullable<bool> TANIMLANDI { get; set; }
    }
}
