//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIHAZ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CIHAZ()
        {
            this.YEMEKHANE_HAREKET = new HashSet<YEMEKHANE_HAREKET>();
            this.YEMEKHANE_HAREKET_RAW = new HashSet<YEMEKHANE_HAREKET_RAW>();
            this.YEMEKHANE_HAREKET_RAW_DEL = new HashSet<YEMEKHANE_HAREKET_RAW_DEL>();
        }
    
        public int CIHAZID { get; set; }
        public string CIHAZADI { get; set; }
        public Nullable<int> CIHAZTIPID { get; set; }
        public string ClientIP { get; set; }
        public Nullable<int> ClientTcpPort { get; set; }
        public Nullable<int> ClientUdpPort { get; set; }
        public string GWAdr { get; set; }
        public string IPAdr { get; set; }
        public string Mac { get; set; }
        public string Name { get; set; }
        public string SMAdr { get; set; }
        public Nullable<int> TcpPort { get; set; }
        public Nullable<int> UdpPort { get; set; }
        public Nullable<int> SerialAddress { get; set; }
        public Nullable<int> SerialBaudRate { get; set; }
        public string SerialCommType { get; set; }
        public Nullable<int> LAST_LOG_INDEX { get; set; }
        public Nullable<decimal> DOLULUK_ORANI { get; set; }
        public bool AKTIF { get; set; }
        public string VERSIYON { get; set; }
        public string YON { get; set; }
        public string TARIFELER { get; set; }
    
        public virtual CIHAZTIP CIHAZTIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEMEKHANE_HAREKET> YEMEKHANE_HAREKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEMEKHANE_HAREKET_RAW> YEMEKHANE_HAREKET_RAW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEMEKHANE_HAREKET_RAW_DEL> YEMEKHANE_HAREKET_RAW_DEL { get; set; }
    }
}
