//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIHAZYETKIBILET
    {
        public int ID { get; set; }
        public Nullable<int> CIHAZID { get; set; }
        public Nullable<int> TARIFEID { get; set; }
        public Nullable<int> GECISLIMITI { get; set; }
        public Nullable<int> ARDISIKGECIS { get; set; }
        public Nullable<bool> ANTIPASSBACK { get; set; }
    }
}
