//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIHAZTARIFE
    {
        public int ID { get; set; }
        public Nullable<int> CIHAZID { get; set; }
        public Nullable<int> TARIFEID { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<decimal> TUTAR2 { get; set; }
        public Nullable<decimal> TUTAR3 { get; set; }
        public Nullable<decimal> TUTAR4 { get; set; }
        public Nullable<decimal> TUTAR5 { get; set; }
        public string TUTAR6 { get; set; }
        public Nullable<int> TEKRAR_OKUMA_SURESI { get; set; }
        public Nullable<int> ZAMAN_ASIMI { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    }
}
