//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string MacAddress { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> TcpPort { get; set; }
        public Nullable<int> UdpPort { get; set; }
        public string Version { get; set; }
    }
}
