//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FFSaleEntities : DbContext
    {
        public FFSaleEntities()
            : base("name=FFSaleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AAA_Test> AAA_Test { get; set; }
        public virtual DbSet<Acente> Acente { get; set; }
        public virtual DbSet<AcenteKullanici> AcenteKullanici { get; set; }
        public virtual DbSet<AcenteTipi> AcenteTipi { get; set; }
        public virtual DbSet<AR_Bileklik> AR_Bileklik { get; set; }
        public virtual DbSet<AR_BileklikTarife> AR_BileklikTarife { get; set; }
        public virtual DbSet<AR_HizmetTuru> AR_HizmetTuru { get; set; }
        public virtual DbSet<AR_Kiosk> AR_Kiosk { get; set; }
        public virtual DbSet<AR_Kullanici> AR_Kullanici { get; set; }
        public virtual DbSet<AR_KullaniciOturum> AR_KullaniciOturum { get; set; }
        public virtual DbSet<AR_KurumTuru> AR_KurumTuru { get; set; }
        public virtual DbSet<AR_Lokasyon> AR_Lokasyon { get; set; }
        public virtual DbSet<AR_Operator> AR_Operator { get; set; }
        public virtual DbSet<AR_Parametre> AR_Parametre { get; set; }
        public virtual DbSet<AR_Rezervasyon> AR_Rezervasyon { get; set; }
        public virtual DbSet<Banka> Banka { get; set; }
        public virtual DbSet<BILET> BILET { get; set; }
        public virtual DbSet<BILET_OZEL> BILET_OZEL { get; set; }
        public virtual DbSet<BILET_TARIFE> BILET_TARIFE { get; set; }
        public virtual DbSet<BiletKota> BiletKota { get; set; }
        public virtual DbSet<BiletKotaKod> BiletKotaKod { get; set; }
        public virtual DbSet<BiletTalep> BiletTalep { get; set; }
        public virtual DbSet<BiletTarife> BiletTarife { get; set; }
        public virtual DbSet<BOLUM> BOLUM { get; set; }
        public virtual DbSet<CIHAZ> CIHAZ { get; set; }
        public virtual DbSet<CIHAZTIP> CIHAZTIP { get; set; }
        public virtual DbSet<DOVIZ> DOVIZ { get; set; }
        public virtual DbSet<FAKULTE> FAKULTE { get; set; }
        public virtual DbSet<HARCAMA_NOKTASI> HARCAMA_NOKTASI { get; set; }
        public virtual DbSet<HEDIYELIKESYA> HEDIYELIKESYA { get; set; }
        public virtual DbSet<ISLEMLER> ISLEMLER { get; set; }
        public virtual DbSet<KAFETERYA_URUN> KAFETERYA_URUN { get; set; }
        public virtual DbSet<KAFETERYA_URUNGRUP> KAFETERYA_URUNGRUP { get; set; }
        public virtual DbSet<KAMPANYA> KAMPANYA { get; set; }
        public virtual DbSet<KAMPUS> KAMPUS { get; set; }
        public virtual DbSet<KartKota> KartKota { get; set; }
        public virtual DbSet<KartKotaKod> KartKotaKod { get; set; }
        public virtual DbSet<KARTLAR> KARTLAR { get; set; }
        public virtual DbSet<KARTLAR_DEMO> KARTLAR_DEMO { get; set; }
        public virtual DbSet<KARTSERI> KARTSERI { get; set; }
        public virtual DbSet<KartTarife> KartTarife { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciOturum> KullaniciOturum { get; set; }
        public virtual DbSet<MailLog> MailLog { get; set; }
        public virtual DbSet<PARAMETRELER> PARAMETRELER { get; set; }
        public virtual DbSet<PERSONEL> PERSONEL { get; set; }
        public virtual DbSet<PERSONEL_TARIFE> PERSONEL_TARIFE { get; set; }
        public virtual DbSet<PERSONEL_TIPLERI> PERSONEL_TIPLERI { get; set; }
        public virtual DbSet<PSWD> PSWD { get; set; }
        public virtual DbSet<PSWD_SESSION> PSWD_SESSION { get; set; }
        public virtual DbSet<Rehber> Rehber { get; set; }
        public virtual DbSet<RehberKota> RehberKota { get; set; }
        public virtual DbSet<SATIS_NOKTASI> SATIS_NOKTASI { get; set; }
        public virtual DbSet<SmtpInfo> SmtpInfo { get; set; }
        public virtual DbSet<Sozlesme> Sozlesme { get; set; }
        public virtual DbSet<Tbl_001_Client_Query_Event> Tbl_001_Client_Query_Event { get; set; }
        public virtual DbSet<Tbl_001_Kart_Logs> Tbl_001_Kart_Logs { get; set; }
        public virtual DbSet<Tbl_001_Server_Query_Event> Tbl_001_Server_Query_Event { get; set; }
        public virtual DbSet<Tbl_001_Tables_Compare> Tbl_001_Tables_Compare { get; set; }
        public virtual DbSet<Tbl_001_Values> Tbl_001_Values { get; set; }
        public virtual DbSet<Tbl_001_YUKLEME_NOKTASI_AND_Kullanici> Tbl_001_YUKLEME_NOKTASI_AND_Kullanici { get; set; }
        public virtual DbSet<VergiDairesi> VergiDairesi { get; set; }
        public virtual DbSet<YAZICI_SABLON> YAZICI_SABLON { get; set; }
        public virtual DbSet<YUKLEME_NOKTASI> YUKLEME_NOKTASI { get; set; }
        public virtual DbSet<ADRES_BILGILERI> ADRES_BILGILERI { get; set; }
        public virtual DbSet<AKTIVASYON> AKTIVASYON { get; set; }
        public virtual DbSet<BAKIYE_YUKLEME> BAKIYE_YUKLEME { get; set; }
        public virtual DbSet<BAKIYE_YUKLEME_BONUS_TANIM> BAKIYE_YUKLEME_BONUS_TANIM { get; set; }
        public virtual DbSet<BAKIYE_YUKLEME_COP> BAKIYE_YUKLEME_COP { get; set; }
        public virtual DbSet<BAKIYE_YUKLEME_DUZELTME> BAKIYE_YUKLEME_DUZELTME { get; set; }
        public virtual DbSet<BAKIYE_YUKLEME_IADE> BAKIYE_YUKLEME_IADE { get; set; }
        public virtual DbSet<BILET_DUZELTME> BILET_DUZELTME { get; set; }
        public virtual DbSet<BILET_ODEME> BILET_ODEME { get; set; }
        public virtual DbSet<BILET_SABLON> BILET_SABLON { get; set; }
        public virtual DbSet<BILET_TARIFE_SABLON> BILET_TARIFE_SABLON { get; set; }
        public virtual DbSet<BILET_TARIFE_YETKI> BILET_TARIFE_YETKI { get; set; }
        public virtual DbSet<BURS> BURS { get; set; }
        public virtual DbSet<CIHAZTARIFE> CIHAZTARIFE { get; set; }
        public virtual DbSet<CIHAZYETKIBILET> CIHAZYETKIBILET { get; set; }
        public virtual DbSet<CIHAZYETKIKART> CIHAZYETKIKART { get; set; }
        public virtual DbSet<GECISBILET> GECISBILET { get; set; }
        public virtual DbSet<GECISKART> GECISKART { get; set; }
        public virtual DbSet<GRUP> GRUP { get; set; }
        public virtual DbSet<GRUPTANIM> GRUPTANIM { get; set; }
        public virtual DbSet<HAREKET> HAREKET { get; set; }
        public virtual DbSet<HEDIYELIKESYASATIS> HEDIYELIKESYASATIS { get; set; }
        public virtual DbSet<KAFETERYA_SATIS> KAFETERYA_SATIS { get; set; }
        public virtual DbSet<KAFETERYA_SATISURUN> KAFETERYA_SATISURUN { get; set; }
        public virtual DbSet<KAFETERYA_STOK> KAFETERYA_STOK { get; set; }
        public virtual DbSet<KAFETERYA_URUN_YETKI> KAFETERYA_URUN_YETKI { get; set; }
        public virtual DbSet<KAMPANYAKOD> KAMPANYAKOD { get; set; }
        public virtual DbSet<KAMPANYATARIFE> KAMPANYATARIFE { get; set; }
        public virtual DbSet<KARALISTE> KARALISTE { get; set; }
        public virtual DbSet<KARTLAR_DUZELTME> KARTLAR_DUZELTME { get; set; }
        public virtual DbSet<KARTLAR_OZEL> KARTLAR_OZEL { get; set; }
        public virtual DbSet<KARTPUAN> KARTPUAN { get; set; }
        public virtual DbSet<KARTPUANDETAY> KARTPUANDETAY { get; set; }
        public virtual DbSet<KARTPUANYUKLEME> KARTPUANYUKLEME { get; set; }
        public virtual DbSet<KIMLIK_BILGILERI> KIMLIK_BILGILERI { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<OZELGECIS> OZELGECIS { get; set; }
        public virtual DbSet<PERSONEL_TARIFE_KAMPANYA> PERSONEL_TARIFE_KAMPANYA { get; set; }
        public virtual DbSet<PERSONEL_TARIFE_YETKI> PERSONEL_TARIFE_YETKI { get; set; }
        public virtual DbSet<SYSTEMLOG> SYSTEMLOG { get; set; }
        public virtual DbSet<USERLOG> USERLOG { get; set; }
        public virtual DbSet<YEMEKHANE_HAREKET> YEMEKHANE_HAREKET { get; set; }
        public virtual DbSet<YEMEKHANE_HAREKET_KIOSK> YEMEKHANE_HAREKET_KIOSK { get; set; }
        public virtual DbSet<YEMEKHANE_HAREKET_RAW> YEMEKHANE_HAREKET_RAW { get; set; }
        public virtual DbSet<YEMEKHANE_HAREKET_RAW_DEL> YEMEKHANE_HAREKET_RAW_DEL { get; set; }
        public virtual DbSet<YEMEKHANE_HAREKET_RAW_DUZELTME> YEMEKHANE_HAREKET_RAW_DUZELTME { get; set; }
        public virtual DbSet<YETKI> YETKI { get; set; }
        public virtual DbSet<YETKIT> YETKIT { get; set; }
    }
}
