//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class GECISKART
    {
        public int ID { get; set; }
        public Nullable<long> KARTID { get; set; }
        public Nullable<int> CIHAZID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<bool> SONUC { get; set; }
        public Nullable<bool> GECTI { get; set; }
        public string YON { get; set; }
        public string STATUS { get; set; }
    }
}
