//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class HARCAMA_NOKTASI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HARCAMA_NOKTASI()
        {
            this.YEMEKHANE_HAREKET_KIOSK = new HashSet<YEMEKHANE_HAREKET_KIOSK>();
        }
    
        public int ID { get; set; }
        public string HARNOKID { get; set; }
        public string HARNOKADI { get; set; }
        public bool AKTIF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEMEKHANE_HAREKET_KIOSK> YEMEKHANE_HAREKET_KIOSK { get; set; }
    }
}
