//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAREKET
    {
        public int ID { get; set; }
        public string ISLEMID { get; set; }
        public string VALSTR1 { get; set; }
        public string VALSTR2 { get; set; }
        public string VALSTR3 { get; set; }
        public string VALSTR4 { get; set; }
        public string VALSTR5 { get; set; }
        public string VALSTR6 { get; set; }
        public string VALSTR7 { get; set; }
        public string VALSTR8 { get; set; }
        public string VALSTR9 { get; set; }
        public string VALSTR10 { get; set; }
        public Nullable<decimal> VALDEC1 { get; set; }
        public Nullable<decimal> VALDEC2 { get; set; }
        public Nullable<decimal> VALDEC3 { get; set; }
        public Nullable<decimal> VALDEC4 { get; set; }
        public Nullable<decimal> VALDEC5 { get; set; }
        public Nullable<decimal> VALDEC6 { get; set; }
        public Nullable<decimal> VALDEC7 { get; set; }
        public Nullable<decimal> VALDEC8 { get; set; }
        public Nullable<decimal> VALDEC9 { get; set; }
        public Nullable<decimal> VALDEC10 { get; set; }
        public string SICILNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    
        public virtual ISLEMLER ISLEMLER { get; set; }
    }
}
