//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEDIYELIKESYA
    {
        public int ID { get; set; }
        public string URUNKODU { get; set; }
        public string BARKODNO { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<int> PUAN { get; set; }
    }
}
