//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAFETERYA_SATIS
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SATISID { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
        public Nullable<decimal> NAKIT { get; set; }
        public Nullable<decimal> KART { get; set; }
        public Nullable<decimal> PARAUSTU { get; set; }
        public string YUKNOKID { get; set; }
        public string SICILNO { get; set; }
        public Nullable<bool> ONAY { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> VERGISIZ { get; set; }
        public Nullable<long> KARTID { get; set; }
        public Nullable<int> ESKI_BAKIYE { get; set; }
        public Nullable<int> HARCANAN_BAKIYE { get; set; }
        public Nullable<int> YENI_BAKIYE { get; set; }
        public Nullable<System.DateTime> IADE_TARIH { get; set; }
        public string IADE_SICILNO { get; set; }
        public string IADE_YUKNOKID { get; set; }
    }
}
