//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAFETERYA_URUNGRUP
    {
        public int URUNGRUPKODU { get; set; }
        public string URUNGRUPADI { get; set; }
        public Nullable<int> POSKODU { get; set; }
        public Nullable<decimal> KDV { get; set; }
    }
}
