//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAFETERYA_SATISURUN
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string SATISID { get; set; }
        public string BARKODNO { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> TOPLAM { get; set; }
        public string YUKNOKID { get; set; }
        public string SICILNO { get; set; }
        public Nullable<decimal> FIYATKDV { get; set; }
        public Nullable<decimal> FIYATVERGISIZ { get; set; }
        public Nullable<decimal> TOPLAMKDV { get; set; }
        public Nullable<decimal> TOPLAMVERGISIZ { get; set; }
        public string SATIS_BARKOD { get; set; }
    }
}
