//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMPANYATARIFE
    {
        public int ID { get; set; }
        public string KAMPANYAID { get; set; }
        public Nullable<byte> TARIFEID { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public string TURU { get; set; }
    }
}
