//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMPANYA
    {
        public int ID { get; set; }
        public string KAMPANYAID { get; set; }
        public Nullable<System.DateTime> BASTAR { get; set; }
        public Nullable<System.DateTime> BITTAR { get; set; }
        public string SICILNO { get; set; }
        public Nullable<System.DateTime> SONDEGISIKLIK { get; set; }
        public string ACIKLAMA { get; set; }
    }
}
