//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMPANYAKOD
    {
        public int ID { get; set; }
        public string KAMPANYAID { get; set; }
        public string KAMPANYAKODU { get; set; }
        public Nullable<bool> KULLANILDIMI { get; set; }
        public Nullable<System.DateTime> KULLANILMATARIHI { get; set; }
        public Nullable<System.DateTime> OLUSTURULMATARIHI { get; set; }
    }
}
