//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARTLAR_OZEL
    {
        public int ID { get; set; }
        public string KARTID { get; set; }
        public string CIHAZLAR { get; set; }
        public Nullable<System.DateTime> BASLANGIC { get; set; }
        public Nullable<System.DateTime> BITIS { get; set; }
        public Nullable<int> GECISLIMITI { get; set; }
        public Nullable<int> ARDISIKGECIS { get; set; }
        public Nullable<bool> ANTIPASSBACK { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<int> ODEMEID { get; set; }
    }
}
