//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARTPUANDETAY
    {
        public int ID { get; set; }
        public Nullable<int> ISLEMID { get; set; }
        public string KARTID { get; set; }
        public string BARKODNO { get; set; }
        public Nullable<int> PUAN { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string YUKNOKID { get; set; }
        public string SICILNO { get; set; }
    }
}
