//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class KIMLIK_BILGILERI
    {
        public int ID { get; set; }
        public int PERID { get; set; }
        public string KIMLIK_TCNO { get; set; }
        public string KIMLIK_BABA { get; set; }
        public string KIMLIK_ANA { get; set; }
        public string KIMLIK_DOGUMYERI { get; set; }
        public Nullable<System.DateTime> KIMLIK_DOGUMTARIHI { get; set; }
        public string KIMLIK_SERI { get; set; }
        public string KIMLIK_NO { get; set; }
        public string KIMLIK_MEDENIHAL { get; set; }
        public string KIMLIK_DINI { get; set; }
        public string KIMLIK_KANGRUBU { get; set; }
        public string KIMLIK_IL { get; set; }
        public string KIMLIK_ILCE { get; set; }
        public string KIMLIK_MAHALLE { get; set; }
        public string KIMLIK_CILTNO { get; set; }
        public string KIMLIK_AILESIRANO { get; set; }
        public string KIMLIK_SIRANO { get; set; }
        public string KIMLIK_VERILDIGIYER { get; set; }
        public string KIMLIK_VERILISNEDENI { get; set; }
        public string KIMLIK_KAYITNO { get; set; }
        public Nullable<System.DateTime> KIMLIK_VERILISTARIHI { get; set; }
    
        public virtual PERSONEL PERSONEL { get; set; }
    }
}
