//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciOturum
    {
        public int Id { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public string OturumId { get; set; }
        public Nullable<System.DateTime> GirisZamani { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
