//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int ID { get; set; }
        public Nullable<int> ISLEM { get; set; }
        public string DETAY { get; set; }
        public string DETAY2 { get; set; }
        public string DETAY3 { get; set; }
        public string DETAY4 { get; set; }
        public string DETAY5 { get; set; }
        public string DETAY6 { get; set; }
        public string DETAY7 { get; set; }
        public string SICILNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
    }
}
