//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailLog
    {
        public int Id { get; set; }
        public string MailType { get; set; }
        public int AcenteId { get; set; }
        public string MailTo { get; set; }
        public string MailBody { get; set; }
        public string Dscr { get; set; }
        public short Status { get; set; }
        public System.DateTime TranDate { get; set; }
    
        public virtual Acente Acente { get; set; }
    }
}
