//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieBookingSerialReservation
    {
        public int MovieBookingSerialReservationId { get; set; }
        public string SerialNumber { get; set; }
        public string ReservationId { get; set; }
        public Nullable<int> MovieTheatrePlaceTemplateDetailsId { get; set; }
        public Nullable<bool> Used { get; set; }
        public string Description { get; set; }
        public Nullable<int> MovieSessionBookingDetailId { get; set; }
        public Nullable<int> MovieSessionId { get; set; }
    }
}
