//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTheatrePlaceTemplateDetailsLog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string BranchName { get; set; }
        public string SeatName { get; set; }
        public Nullable<int> State { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<bool> IsSend { get; set; }
    }
}
