//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTheaterLog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string CityName { get; set; }
        public string TownName { get; set; }
        public string Address { get; set; }
        public string AvmName { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> State { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<bool> IsSend { get; set; }
    }
}
