//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRELER
    {
        public string PARAMETRE { get; set; }
        public Nullable<long> BIGINT { get; set; }
        public Nullable<bool> BIT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> DATETIME { get; set; }
        public Nullable<decimal> DECIMAL { get; set; }
        public Nullable<int> INT { get; set; }
        public Nullable<decimal> MONEY { get; set; }
        public string NTEXT { get; set; }
        public Nullable<System.TimeSpan> TIME { get; set; }
    }
}
