//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL_TARIFE
    {
        public Nullable<int> PERTIPID { get; set; }
        public byte TARIFEID { get; set; }
        public string TARIFEADI { get; set; }
        public Nullable<byte> SABAH { get; set; }
        public Nullable<decimal> SABAH1 { get; set; }
        public Nullable<decimal> SABAH2 { get; set; }
        public Nullable<decimal> SABAH3 { get; set; }
        public Nullable<decimal> SABAH_REEL { get; set; }
        public Nullable<byte> OGLE { get; set; }
        public Nullable<decimal> OGLE1 { get; set; }
        public Nullable<decimal> OGLE2 { get; set; }
        public Nullable<decimal> OGLE3 { get; set; }
        public Nullable<decimal> OGLE_REEL { get; set; }
        public Nullable<byte> AKSAM { get; set; }
        public Nullable<decimal> AKSAM1 { get; set; }
        public Nullable<decimal> AKSAM2 { get; set; }
        public Nullable<decimal> AKSAM3 { get; set; }
        public Nullable<decimal> AKSAM_REEL { get; set; }
        public Nullable<bool> BAKIYEYUKLEME { get; set; }
        public Nullable<bool> DEPOZITOLU { get; set; }
        public Nullable<decimal> DEPOZITOTUTAR { get; set; }
        public Nullable<int> GECERLILIKGUN { get; set; }
        public Nullable<bool> DEMO { get; set; }
        public Nullable<bool> PUAN { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
        public Nullable<decimal> EKDEPOZITO { get; set; }
    
        public virtual PERSONEL_TIPLERI PERSONEL_TIPLERI { get; set; }
    }
}
