//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONEL()
        {
            this.KARTLAR = new HashSet<KARTLAR>();
            this.ADRES_BILGILERI = new HashSet<ADRES_BILGILERI>();
            this.KIMLIK_BILGILERI = new HashSet<KIMLIK_BILGILERI>();
            this.YEMEKHANE_HAREKET_KIOSK = new HashSet<YEMEKHANE_HAREKET_KIOSK>();
        }
    
        public int PERID { get; set; }
        public string SICILNO { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public Nullable<int> BOLUMID { get; set; }
        public Nullable<int> PERTIPID { get; set; }
        public Nullable<byte> TARIFEID { get; set; }
        public Nullable<System.DateTime> GECERLILIK_BASLANGIC { get; set; }
        public Nullable<System.DateTime> GECERLILIK_BITIS { get; set; }
        public byte CINSIYET { get; set; }
        public bool AKTIF { get; set; }
        public string GOREV { get; set; }
    
        public virtual BOLUM BOLUM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KARTLAR> KARTLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADRES_BILGILERI> ADRES_BILGILERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KIMLIK_BILGILERI> KIMLIK_BILGILERI { get; set; }
        public virtual PERSONEL_TIPLERI PERSONEL_TIPLERI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEMEKHANE_HAREKET_KIOSK> YEMEKHANE_HAREKET_KIOSK { get; set; }
    }
}
