//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSWD
    {
        public int ID { get; set; }
        public string ADI { get; set; }
        public string SICILNO { get; set; }
        public string SIFRE { get; set; }
        public string EMAIL { get; set; }
        public string DIL { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public string PARMAKIZI { get; set; }
        public string TARIFELER_BILET { get; set; }
        public string TARIFELER_KART { get; set; }
        public string SESSIONID { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
