//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSWD_SESSION
    {
        public string USERID { get; set; }
        public string SESSIONID { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public Nullable<System.DateTime> DATEEXPIRED { get; set; }
    }
}
