//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sozlesme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sozlesme()
        {
            this.BiletKota = new HashSet<BiletKota>();
            this.KartKota = new HashSet<KartKota>();
        }
    
        public int SozlesmeId { get; set; }
        public int AcenteId { get; set; }
        public System.DateTime GecerlilikBaslangic { get; set; }
        public System.DateTime GecerlilikBitis { get; set; }
        public string Aciklama { get; set; }
        public byte[] Dosya { get; set; }
        public bool Aktif { get; set; }
    
        public virtual Acente Acente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BiletKota> BiletKota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KartKota> KartKota { get; set; }
    }
}
