//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_001_Tables_Compare
    {
        public long ID { get; set; }
        public Nullable<int> Table_Name { get; set; }
        public Nullable<int> Table_Type { get; set; }
        public Nullable<int> YUKLEME_NOKTASI_ID { get; set; }
        public Nullable<int> Period_Minute { get; set; }
        public Nullable<int> Try_Again_Minute { get; set; }
        public Nullable<int> Try_Again_Number { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
    }
}
