//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_001_Client_Query_Event
    {
        public int ID { get; set; }
        public string Pars_Key_Value { get; set; }
        public string Query_String { get; set; }
        public string YUKNOKID { get; set; }
        public string SICILNO { get; set; }
        public string Client_ID { get; set; }
        public Nullable<int> Status_ { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
    }
}
