//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_001_Values
    {
        public int ID { get; set; }
        public Nullable<int> Main_ID { get; set; }
        public string Value_Code { get; set; }
        public string Value_Name { get; set; }
        public string Parameter1 { get; set; }
        public string Parameter2 { get; set; }
        public string Parameter3 { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
    }
}
