//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class VergiDairesi
    {
        public int Id { get; set; }
        public string VergiDairesiNo { get; set; }
        public string VergiDairesiAdi { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
    }
}
