//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEMEKHANE_HAREKET_RAW
    {
        public int ID { get; set; }
        public Nullable<int> CIHAZID { get; set; }
        public string Balance { get; set; }
        public string CardID { get; set; }
        public string DvcIP { get; set; }
        public string Fee { get; set; }
        public Nullable<bool> FeedBack { get; set; }
        public Nullable<int> Index { get; set; }
        public string SpecialData { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Times { get; set; }
        public string UserType { get; set; }
        public Nullable<System.DateTime> ZAMAN { get; set; }
        public Nullable<int> YEMEK_FIYATI { get; set; }
        public Nullable<int> DEVLETIN_ODEDIGI { get; set; }
        public string SICILNO { get; set; }
        public string VERSIYON { get; set; }
        public Nullable<int> PERID { get; set; }
    
        public virtual CIHAZ CIHAZ { get; set; }
    }
}
