//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEMEKHANE_HAREKET
    {
        public int ID { get; set; }
        public Nullable<long> KARTID { get; set; }
        public Nullable<int> DUSULEN_BAKIYE { get; set; }
        public Nullable<int> KALAN_BAKIYE { get; set; }
        public Nullable<int> CIHAZID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<System.DateTime> ZAMAN { get; set; }
        public Nullable<int> YEMEK_FIYATI { get; set; }
        public Nullable<int> DEVLETIN_ODEDIGI { get; set; }
        public string SICILNO { get; set; }
    
        public virtual CIHAZ CIHAZ { get; set; }
    }
}
