//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class YETKI
    {
        public string GRUPNO { get; set; }
        public string SICILNO { get; set; }
        public string PARAMNO { get; set; }
        public Nullable<int> DEGER { get; set; }
    }
}
