//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineBookEntities : DbContext
    {
        public CineBookEntities()
            : base("name=CineBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<ModuleAuth> ModuleAuth { get; set; }
        public virtual DbSet<ModuleOperation> ModuleOperation { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Movie_MovieCast> Movie_MovieCast { get; set; }
        public virtual DbSet<Movie_MovieCategory> Movie_MovieCategory { get; set; }
        public virtual DbSet<Movie_MovieDirector> Movie_MovieDirector { get; set; }
        public virtual DbSet<Movie_MovieFormat> Movie_MovieFormat { get; set; }
        public virtual DbSet<Movie_MovieType> Movie_MovieType { get; set; }
        public virtual DbSet<MovieCast> MovieCast { get; set; }
        public virtual DbSet<MovieCategory> MovieCategory { get; set; }
        public virtual DbSet<MovieDirector> MovieDirector { get; set; }
        public virtual DbSet<MovieFormat> MovieFormat { get; set; }
        public virtual DbSet<MovieSeatType> MovieSeatType { get; set; }
        public virtual DbSet<MovieSession> MovieSession { get; set; }
        public virtual DbSet<MovieSession_MovieFormat> MovieSession_MovieFormat { get; set; }
        public virtual DbSet<MovieSessionReservation> MovieSessionReservation { get; set; }
        public virtual DbSet<MovieTariff> MovieTariff { get; set; }
        public virtual DbSet<MovieTheater> MovieTheater { get; set; }
        public virtual DbSet<MovieTheatrePlace> MovieTheatrePlace { get; set; }
        public virtual DbSet<MovieTheatrePlaceTemplate> MovieTheatrePlaceTemplate { get; set; }
        public virtual DbSet<MovieTheatrePlaceTemplateDetails> MovieTheatrePlaceTemplateDetails { get; set; }
        public virtual DbSet<MovieTicket> MovieTicket { get; set; }
        public virtual DbSet<MovieTicketOption> MovieTicketOption { get; set; }
        public virtual DbSet<MovieTicketSale> MovieTicketSale { get; set; }
        public virtual DbSet<MovieTicketSaleOption> MovieTicketSaleOption { get; set; }
        public virtual DbSet<MovieTicketSalePayment> MovieTicketSalePayment { get; set; }
        public virtual DbSet<MovieTicketSalePaymentType> MovieTicketSalePaymentType { get; set; }
        public virtual DbSet<MovieType> MovieType { get; set; }
        public virtual DbSet<PrinterTemplate> PrinterTemplate { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemParameter> SystemParameter { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
        public virtual DbSet<UserGroup_User> UserGroup_User { get; set; }
        public virtual DbSet<UserSession> UserSession { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<MovieTicketDeleted> MovieTicketDeleted { get; set; }
        public virtual DbSet<MovieTicketSaleDeleted> MovieTicketSaleDeleted { get; set; }
        public virtual DbSet<MovieTicketSaleOptionDeleted> MovieTicketSaleOptionDeleted { get; set; }
        public virtual DbSet<MovieTicketSalePaymentDeleted> MovieTicketSalePaymentDeleted { get; set; }
        public virtual DbSet<LabelDictionary> LabelDictionary { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<MovieSessionBooking> MovieSessionBooking { get; set; }
        public virtual DbSet<MovieSessionBookingDetail> MovieSessionBookingDetail { get; set; }
        public virtual DbSet<MovieSessionAmount> MovieSessionAmount { get; set; }
        public virtual DbSet<MovieTheatrePlaceTemplateBlock> MovieTheatrePlaceTemplateBlock { get; set; }
        public virtual DbSet<MovieSessionLog> MovieSessionLog { get; set; }
        public virtual DbSet<MovieTheaterLog> MovieTheaterLog { get; set; }
        public virtual DbSet<MovieTheatrePlaceLog> MovieTheatrePlaceLog { get; set; }
        public virtual DbSet<MovieTheatrePlaceTemplateDetailsLog> MovieTheatrePlaceTemplateDetailsLog { get; set; }
        public virtual DbSet<MovieTicketSaleLog> MovieTicketSaleLog { get; set; }
        public virtual DbSet<MovieTheatrePlaceTemplateDetailsOto> MovieTheatrePlaceTemplateDetailsOto { get; set; }
        public virtual DbSet<MovieTheatrePlaceTemplateDetailsSon> MovieTheatrePlaceTemplateDetailsSon { get; set; }
        public virtual DbSet<MovieTheatrePlaceTemplateDetailsYdk> MovieTheatrePlaceTemplateDetailsYdk { get; set; }
        public virtual DbSet<MovieTheatrePlaceTemplateDetailsYdk2> MovieTheatrePlaceTemplateDetailsYdk2 { get; set; }
        public virtual DbSet<PrinterTemplate_20171210> PrinterTemplate_20171210 { get; set; }
    }
}
