//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSessionLog
    {
        public int Id { get; set; }
        public Nullable<int> MovieSessionId { get; set; }
        public string SaloonName { get; set; }
        public string BranchName { get; set; }
        public Nullable<System.DateTime> SeanceTime { get; set; }
        public string FilmId { get; set; }
        public string VersionName { get; set; }
        public Nullable<int> State { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<bool> IsSend { get; set; }
        public Nullable<int> SgmSessionId { get; set; }
    }
}
