//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieTicketSaleOption
    {
        public int Id { get; set; }
        public int MovieTicketSaleId { get; set; }
        public int TicketOptionId { get; set; }
        public decimal Amount { get; set; }
        public int Count { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual MovieTicketOption MovieTicketOption { get; set; }
        public virtual MovieTicketSale MovieTicketSale { get; set; }
    }
}
