//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSessionBookingDetail
    {
        public int Id { get; set; }
        public int BookingId { get; set; }
        public int MovieSeatTypeId { get; set; }
        public string SeatPrefix { get; set; }
        public string SeatSuffix { get; set; }
        public string SeatCode { get; set; }
        public int MovieTariffId { get; set; }
        public string CustomerInfo { get; set; }
        public Nullable<int> Block { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual MovieSeatType MovieSeatType { get; set; }
        public virtual MovieSessionBooking MovieSessionBooking { get; set; }
    }
}
