//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineBookManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieSessionBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieSessionBooking()
        {
            this.MovieSessionBookingDetail = new HashSet<MovieSessionBookingDetail>();
        }
    
        public int Id { get; set; }
        public string ReservationId { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public int MovieSessionId { get; set; }
        public System.DateTime BookingTime { get; set; }
        public System.DateTime ExpirationTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public string SessionId { get; set; }
        public Nullable<int> MovieTicketSaleId { get; set; }
        public Nullable<System.DateTime> CancellationTime { get; set; }
        public Nullable<int> CancellationUserId { get; set; }
        public string CancellationSessionId { get; set; }
        public string Status { get; set; }
    
        public virtual MovieSession MovieSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieSessionBookingDetail> MovieSessionBookingDetail { get; set; }
    }
}
